services:
  web:
    build: .
    image: progetto_software_avanzata-web:latest
    container_name: progetto_software_avanzata-web-1
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./data:/app/data
      