name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag my-image:$GITHUB_SHA
      - name: Push the Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          run: docker push my-image:$GITHUB_SHA

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the application
        run: npm test

  deploy_staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to staging
        run: kubectl apply -f ./k8s/staging
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_STAGING }}

  deploy_production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: kubectl apply -f ./k8s/production
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_PRODUCTION }}
