name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag my-image:$GITHUB_SHA
      - name: Push the Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          run: docker push my-image:$GITHUB_SHA

  test:
    needs: build
    runs-on: debian:bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Test the application
        run: npm test
      - name: Test the application
        run: pytest
